version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      FLASK_ENV: development
      APP_SETTINGS: config.DevelopmentConfig
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "5000:5000"
    volumes:
      - .:/mutants
    depends_on:
      - db